### ISSUE TITLE
Error in standardize_column_names

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#158] opened 2021-11-03 23:51 UTC
I don't (yet) have a reprex, but have there been any recent changes that might have resulted in the following error when I try to run pk.nca?

```
Error in standardize_column_names(x = data_no_exclude, cols = cols, group_cols = group_cols,  : 
  group_cols must not overlap with other column names
```

**Comment by slyrus** [comment] 2021-11-04 00:23
FWIW, this is the offending commit:
```
b4322c5dc9815e2c2ace61c033acaac395717eb8 is the first bad commit
commit b4322c5dc9815e2c2ace61c033acaac395717eb8
Author: Bill Denney <wdenney@humanpredictions.com>
Date:   Mon Aug 23 16:30:39 2021 -0400

    Simplify PKNCA internals for calculations; side effect of better tibble handling

```

**Comment by billdenney** [comment] 2021-11-04 00:26
With version 0.9.5, I made significant internal changes to make it easier to maintain the code.  It looks like you've hit on something where your group names are conflicting with another column name.  I tried to prevent column name conflicts, but it appears that you found an issue where that protection was incomplete.

Can you share just the code that you're using (specifically the calls to PKNCAconc and PKNCAdose)?  I probably don't need the data to diagnose this one.

**Comment by slyrus** [comment] 2021-11-04 00:39
It's something like this:
```
    ## Create a PKNCAconc object for our pk data
    my.conc <- PKNCA::PKNCAconc(d.conc, Concentration~Time|Animal/Treatment+DoseN+Route)

    ## Create a PKNCAdose object for our dosing schedule
    my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+DoseN+Route)

    ## Create a PKNCAdata object from the conc and dose objects and specify
    ## the desired intervals for which to compute PK parameters
    my.data <- PKNCA::PKNCAdata(my.conc,
                                my.dose,
                                intervals = data.frame(start = c(0),
                                                       end = c(24),
                                                       tlast = TRUE,
                                                       tmax = TRUE,
                                                       cmax = TRUE,
                                                       cmin = TRUE,
                                                       half.life = TRUE,
                                                       auclast = TRUE,
                                                       aucinf.obs = TRUE),
                                options = list(allow.tmax.in.half.life = TRUE,
                                               min.hl.points = 2))
```

**Comment by slyrus** [comment] 2021-11-07 18:36
Any suggestions besides just rolling back?

**Comment by billdenney** [comment] 2021-11-08 14:45
I just got to look at it in more detail, and the issue is that the column `DoseN` is used both for the dose amount and grouping information.

When I made some simple data to reproduce your error (below), that seems to be the issue.  An immediate workaround/fix would be to create a new column named something like `DoseGroup` and assign `DoseN` to that.  Then, use `DoseGroup` as the grouping column.  Immediately, I can make a clearer error message which will tell you what column name is the problem.

I need to think a bit more about if I want to allow a value to be used for both a group and another part of the data.  For coding the internals of PKNCA, it will be a lot easier if a value is only one or the other: group or another part of the data.  For user simplicity, I understand the value of flexibility but I need to think more about the balance of user vs code complexity.

``` r
library(PKNCA)

d.conc <-
  data.frame(
    Time=0:4,
    Concentration=2^(-(1:5)),
    Animal="A",
    Treatment="B",
    DoseN=1,
    Route="extravascular"
  )
d.dose <-
  d.conc[d.conc$Time == 0, ]

my.conc <- PKNCA::PKNCAconc(d.conc, Concentration~Time|Animal/Treatment+DoseN+Route)

## Create a PKNCAdose object for our dosing schedule
my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+DoseN+Route)

## Create a PKNCAdata object from the conc and dose objects and specify
## the desired intervals for which to compute PK parameters
my.data <- PKNCA::PKNCAdata(my.conc,
                            my.dose,
                            intervals = data.frame(start = c(0),
                                                   end = c(24),
                                                   tlast = TRUE,
                                                   tmax = TRUE,
                                                   cmax = TRUE,
                                                   cmin = TRUE,
                                                   half.life = TRUE,
                                                   auclast = TRUE,
                                                   aucinf.obs = TRUE),
                            options = list(allow.tmax.in.half.life = TRUE,
                                           min.hl.points = 2))
pk.nca(my.data)
#> Error in standardize_column_names(x = data_no_exclude, cols = cols, group_cols = group_cols, : group_cols must not overlap with other column names
```

<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

# Workaround

``` r
library(PKNCA)

d.conc <-
  data.frame(
    Time=0:4,
    Concentration=2^(-(1:5)),
    Animal="A",
    Treatment="B",
    DoseN=1,
    Route="extravascular"
  )
d.conc$DoseGroup <- d.conc$DoseN
d.dose <-
  d.conc[d.conc$Time == 0, ]

my.conc <- PKNCA::PKNCAconc(d.conc, Concentration~Time|Animal/Treatment+DoseGroup+Route)

## Create a PKNCAdose object for our dosing schedule
my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+DoseGroup+Route)

## Create a PKNCAdata object from the conc and dose objects and specify
## the desired intervals for which to compute PK parameters
my.data <- PKNCA::PKNCAdata(my.conc,
                            my.dose,
                            intervals = data.frame(start = c(0),
                                                   end = c(24),
                                                   tlast = TRUE,
                                                   tmax = TRUE,
                                                   cmax = TRUE,
                                                   cmin = TRUE,
                                                   half.life = TRUE,
                                                   auclast = TRUE,
                                                   aucinf.obs = TRUE),
                            options = list(allow.tmax.in.half.life = TRUE,
                                           min.hl.points = 2))
my.result <- pk.nca(my.data)
#> Warning in adj.r.squared(r_squared, nrow(data)): n must be > 2 for adj.r.squared
summary(my.result)
#>  start end Treatment DoseGroup         Route N    auclast       cmax
#>      0  24         B         1 extravascular 1 0.676 [NC] 0.500 [NC]
#>         cmin                 tmax             tlast half.life aucinf.obs
#>  0.0312 [NC] 0.000 [0.000, 0.000] 4.00 [4.00, 4.00] 1.00 [NC] 0.721 [NC]
#> 
#> Caption: auclast, cmax, cmin, aucinf.obs: geometric mean and geometric coefficient of variation; tmax, tlast: median and range; half.life: arithmetic mean and standard deviation
```

<sup>Created on 2021-11-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by slyrus** [comment] 2021-11-08 21:20
Well, the message is helpful but I'm still not clear on why we have this check in the first place. Is it "wrong" to have DoseN on both sides of the formula, or is the problem that I'm using DoseN both the PKNAconc and PKNAdose objects?

Arbitrarily repeating the data seems like a hack and I'm trying to understand why I would be the only person to run into this sort of problem. thanks!

**Comment by billdenney** [comment] 2021-11-08 21:32
That's fair.  The last question is the easiest:  You're the only person to run into the problem because the problem is new with version 0.9.5 (which is only a few days old).  Most people are probably either still using 0.9.4.

And, there's nothing inherently "wrong" with using DoseN both as the dose amount and the group.  The issue is new because I'm now nesting the data where the groups stay in an outer data.frame while the rest of the data goes into an inner data.frame (using the `tidyr::nest()` function).

As you point out that it's not inherently wrong, I'm gonna do a more extensive fix that will re-allow the type of group setup you're using.  That will take a bit more time (so, please use the work-around for now...).

**Comment by slyrus** [comment] 2021-11-09 01:11
Thanks for the explanation -- but this still leaves my question as to whether I even need Dose in the second half of the formula. That is (putting aside the Dose/DoseN naming/duplication issue for a moment), is
```
my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+DoseN+Route)
```
basically the same as
```
my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+Route)
```
Or do I need the Dose in the right hand side as well?

**Comment by slyrus** [comment] 2021-11-09 01:19
Showing my continued lack of understanding of what's really going on here, if I do the following:
```
    ## Merge animals and dose.times to create a data frame containing the
    ## dose times and amounts for each animal
    d.dose <- merge(animals, dose.times) %>%
      dplyr::mutate(Dose = DoseN)
    
    d.conc <- pk_nca_data %>%
      tidyr::drop_na(Conc) %>%
      dplyr::rename(Concentration = Conc) %>%
      dplyr::mutate(Dose = DoseN)
  
    ## Create a PKNCAconc object for our pk data
    my.conc <- PKNCA::PKNCAconc(d.conc, Concentration~Time|Animal/Treatment+Dose+Route)

    ## Create a PKNCAdose object for our dosing schedule
    my.dose <- PKNCA::PKNCAdose(d.dose, Dose ~ Time|Animal/Treatment+Route)
```
things work. However, if I rename the columns, instead of copying them with mutate, I get the following error:
```
Error: Names must be unique.
✖ These names are duplicated:
  * "Dose" at locations 2 and 10.
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by billdenney** [comment] 2021-11-09 01:28
> Or do I need the Dose in the right hand side as well?

The most likely answer is that no, you probably don't need  DoseN on the right hand side, and `my.dose <- PKNCA::PKNCAdose(d.dose, DoseN ~ Time|Animal/Treatment+Route)` is likely sufficient.  (The caveat would be if an animal had more than one dose with a given `Treatment` and `Route`, then you could possibly want it.  But, that is uncommon.)

The error you're getting with rename is due to the fact that you apparently already have a column named "Dose" in your dataset.  (Column numbers 2 and 10 would both be named dose.)

**Comment by billdenney** [comment] 2022-05-13 19:47
As I've been working on the sparse NCA part of PKNCA, I've also been thinking about this issue.

Tracking the grouping columns separately from the dosing columns where they could be duplicated gets to be very complicated, very quickly.  "Very complicated" tends to introduce bugs into the software (and maintenance problems down the road).

Because this causes issues which would become hard to untangle down the line, I think I'm going to close this issue.  Hopefully, the workaround of adding another column, when required, will work sufficiently.

**Closed by billdenney** 2022-05-13 19:47 UTC
