### ISSUE TITLE
calculate parameter 

### ISSUE THREAD

**Issue by skyee1** [billdenney/pknca#147] opened 2021-06-20 15:32 UTC
Hello,
PKNCA is a great package. Thanks to the authors for maintaining this for the community.

I try to calculate the parameters of multi dose data. The data are as follows. The route of administration is extravascular. Dose interval is 12h. Dosage is 20mg.

```r
subject <- '102'
day <- rep(c(1,4,5,6),c(13,2,2,25))
time <- c(0:12,0,12,0,12,seq(0,48,by=2))

conc <- c(0,70,150,140,110,100,250,180,130,80,60,50,20,
          10,9.8,9,8,7,6,4,9,27,76,100,97,83,295,203,136,
          90,70,300,203,120,90,72,55,25,15,10,9,6)
dose = 20
tau = 12

data <- data.frame(subject = subject,
                    time = time,
                    day = day,
                    conc = conc,
                    dose = dose,
                    tau = tau)
conc_obj <- PKNCAconc(data, conc~time|subject + day)

d_dose <- unique(data[data$time==0 | data$time==12 ,])

dose_obj <- PKNCAdose(d_dose, dose~time|subject + day)

intervals_manual <-
  data.frame(start=0, end=c(max(data$time),Inf),
             auclast = c(T,F),
             mrt.md.obs = c(F,T),
             cav = c(F,T),
             swing = c(F,T),
             vss.obs = c(F,T),
             aumclast = c(F,T))

data_obj <- PKNCAdata(conc_obj, dose_obj ,intervals= intervals_manual)
results_obj <- pk.nca(data_obj)
```

when I run this code, I receive thr error.
```r
Error in (function (conc, time, volume, duration.conc, dose, time.dose,  : 
  Error with interval subject=102, day=1, start=0, end=Inf: Cannot find argument 'tau' for NCA function 'pk.calc.mrt.md'
```

But if I use the parameter "mrt.obs", its value is different with the result of the software "winnolin".

This problem has puzzled me for a long time, how to calculate specific parameters related to multi dose data when using multi dose data.

Hope to get your reply as soon as possible！

**Comment by billdenney** [comment] 2021-06-20 15:38
Duplicate of #148

**Closed by billdenney** 2021-06-20 15:38 UTC
