### ISSUE TITLE
cohort/pseudo-id needed to work around sparse study designs

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#64] opened 2018-03-26 16:42 UTC
I have a PK study where we take take samples from 2 animals at some early time points, then 2 animals from the next time points, etc... In order to get PKNCA to play nice I've arbitrarily assigned the animals to one of two cohorts. That works and gives me the expected results but isn't as elegant as direct support for sparse designs. This is explicitly addressed https://github.com/billdenney/pknca/issues/1 but I've added this issue as a placeholder for folks who might run into the same issue I have without realizing that what they really need is support for sparse designs.

@billdenney  replied via email to my question saying:

Your method of assigning a pseudo ID is the best way right now.  The right method for handling data like you describe is to use sparse PK methods (one of the older feature requests in the github issues).  PKNCA currently tests data for validity by (among other things) confirming that there is a single measurement for a group at a time point.  With sparse PK methods, the individual (animal or human) isn’t the unit for calculations, the treatment is, so different checks must be performed.

**Comment by billdenney** [comment] 2021-06-07 14:46
As this is a duplicate of #1, closing.

**Closed by billdenney** 2021-06-07 14:46 UTC
